### ISSUE TITLE
Bot crash by delete operation

### ISSUE THREAD

**Issue by Biogen** [wuzzapcom/toussaint#3]
Log: 
Alexandr, [21 Jul 2019 at 23:12:06]:
/search God of War

wuzzapcom test bot, [21 Jul 2019 at 23:12:07]:
1) God of War® III Обновленная версия, 1199 рублей
2) Цифровое расширенное издание God of War™, 3999 рублей
3) God of War: Восхождение™, 679 рублей
4) God of War: Восхождение™ Ultimate Edition, 1199 рублей
5) God of War®: Chains of Olympus, 1069 рублей
6) God of War® Collection Volume II, 1199 рублей
7) God of War®:  Призрак Спарты, 1069 рублей
8) God of War® Collection, 1199 рублей
9) Отменить

Alexandr, [21 Jul 2019 at 23:12:11]:
1

wuzzapcom test bot, [21 Jul 2019 at 23:12:12]:
Вы успешно подписались на уведомления!

Alexandr, [21 Jul 2019 at 23:12:15]:
/list

wuzzapcom test bot, [21 Jul 2019 at 23:12:16]:
Ваши игры:
God of War® III Обновленная версия стоит 1199

Alexandr, [21 Jul 2019 at 23:12:18]:
/help

wuzzapcom test bot, [21 Jul 2019 at 23:12:18]:
/help -- показать это сообщение
/list -- показать список игр, на которые вы подписаны
/sale -- показать список игр со скидкой, на которые вы подписаны
/search [SMTH] - выполнить поиск игры и подписаться на нее
/delete [SMTH] - отписаться от уведомлений на игры

Alexandr, [21 Jul 2019 at 23:12:22 (21/07/2019, 23:12:24)]:
/delete -1

wuzzapcom test bot, [21 Jul 2019 at 23:12:22]:
Удаление не удалось, попробуйте еще раз.

EDIT[_Alexandr, [21 Jul 2019 at 23:12:22 (21/07/2019, 23:12:24)]_ message] : 
/delete 1

Alexandr, [21 Jul 2019 at 23:12:27]:
/delete 1

/list

**Comment by wuzzapcom** [comment]
logs from server:
```
toussaint-telegram_1  | panic: runtime error: invalid memory address or nil pointer dereference
toussaint-telegram_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x69bc1e]
toussaint-telegram_1  |
toussaint-telegram_1  | goroutine 188 [running]:
toussaint-telegram_1  | toussaint/clients/telegram/app/cache.HandleMessage(0x0, 0x82de3ca, 0x774fdc, 0x61, 0x1)
toussaint-telegram_1  |         /go/src/toussaint/clients/telegram/app/cache/cache.go:42 +0x3e
toussaint-telegram_1  | toussaint/clients/telegram/app.(*Telegram).Start.func1(0xd0c9168, 0x0, 0xc000248280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
toussaint-telegram_1  |         /go/src/toussaint/clients/telegram/app/telegram.go:57 +0x2f
toussaint-telegram_1  | created by toussaint/clients/telegram/app.(*Telegram).Start
toussaint-telegram_1  |         /go/src/toussaint/clients/telegram/app/telegram.go:56 +0x183
toussaint-telegram_1  | wtf id is 1wtf id is 2wtf id is 1wtf id is 1toussaint-backend_1   | net/http.HandlerFunc.ServeHTTP(0x7ec440, 0x837680, 0xc0000ea000, 0xc0000fc500)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:1964 +0x44
toussaint-backend_1   | toussaint/backend/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000e20c0, 0x837680, 0xc0000ea000, 0xc0000fc300)
toussaint-backend_1   |         /go/src/toussaint/backend/vendor/github.com/gorilla/mux/mux.go:212 +0xd0
toussaint-backend_1   | net/http.serverHandler.ServeHTTP(0xc0000652b0, 0x837680, 0xc0000ea000, 0xc0000fc300)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:2741 +0xab
toussaint-backend_1   | net/http.(*conn).serve(0xc000384f00, 0x837ac0, 0xc00004da00)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:1847 +0x646
toussaint-backend_1   | created by net/http.(*Server).Serve
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:2851 +0x2f5
toussaint-backend_1   | 2019/07/21 20:06:01 http: panic serving 172.18.0.2:46906: interface conversion: interface {} is nil, not string
toussaint-backend_1   | goroutine 95 [running]:
toussaint-backend_1   | net/http.(*conn).serve.func1(0xc0003845a0)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:1746 +0xd0
toussaint-backend_1   | panic(0x773160, 0xc000176510)
toussaint-backend_1   |         /usr/local/go/src/runtime/panic.go:513 +0x1b9
toussaint-backend_1   | toussaint/backend/app.parseSingleGame(0xc00057f5f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
toussaint-backend_1   |         /go/src/toussaint/backend/app/psn.go:121 +0x999
toussaint-backend_1   | toussaint/backend/app.parseSearchAnswer(0xc000424000, 0xf1af, 0xfe00, 0xf1af, 0xfe00, 0x0, 0x0, 0xc00056565f)
toussaint-backend_1   |         /go/src/toussaint/backend/app/psn.go:159 +0x308
toussaint-backend_1   | toussaint/backend/app.searchByName(0xc000565664, 0x7, 0x4, 0xc000565664, 0x7, 0x0, 0x74e401)
toussaint-backend_1   |         /go/src/toussaint/backend/app/psn.go:190 +0x213
toussaint-backend_1   | toussaint/backend/app.handleSearch(0x837680, 0xc0000ea380, 0xc0000fc400)
toussaint-backend_1   |         /go/src/toussaint/backend/app/rest.go:24 +0x97
toussaint-backend_1   | net/http.HandlerFunc.ServeHTTP(0x7ec440, 0x837680, 0xc0000ea380, 0xc0000fc400)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:1964 +0x44
toussaint-backend_1   | toussaint/backend/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000e20c0, 0x837680, 0xc0000ea380, 0xc0000fc100)
toussaint-backend_1   |         /go/src/toussaint/backend/vendor/github.com/gorilla/mux/mux.go:212 +0xd0
toussaint-backend_1   | net/http.serverHandler.ServeHTTP(0xc0000652b0, 0x837680, 0xc0000ea380, 0xc0000fc100)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:2741 +0xab
toussaint-backend_1   | net/http.(*conn).serve(0xc0003845a0, 0x837ac0, 0xc000536d80)
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:1847 +0x646
toussaint-backend_1   | created by net/http.(*Server).Serve
toussaint-backend_1   |         /usr/local/go/src/net/http/server.go:2851 +0x2f5
toussaint-backend_1   | 2019/07/21 20:08:25 [ERR] GET /games: game not found
toussaint-backend_1   | 2019/07/21 20:08:25 [ERR] DELETE /notifications: field game-id not found in query parameters
toussaint-backend_1   | 2019/07/21 20:08:25 http: multiple response.WriteHeader calls
toussaint-backend_1   | 2019/07/21 20:12:22 [ERR] GET /games: game not found
toussaint-backend_1   | 2019/07/21 20:12:22 [ERR] DELETE /notifications: field game-id not found in query parameters
toussaint-backend_1   | 2019/07/21 20:12:22 http: multiple response.WriteHeader calls
toussaint-backend_1   | 2019/07/21 20:12:24 Removed client. 0 registered clients
```
